services {
    service PaymentService {
        type simple;
        endpoint 127.0.0.1:8080;
        amqp_channel 1;
        latency_threshold 50.0;
    }
    service InventoryService {
        type simple;
        endpoint 127.0.0.1:8081;
        amqp_channel 2;
        latency_threshold 100.0;
    }
    service AnalysisService {
        type composition;
        entry_point 127.0.0.1:8082;
        services {
            service MathNode {
                order 1;
            }
            service GraphNode {
                order 2;
                serialized false;
            }
        }
    }
}
